version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - MYSQLHOST=crossover.proxy.rlwy.net
      - MYSQLUSER=root
      - MYSQLPASSWORD=HklMpAMgktuUeJVWWImttcQqcPObNVmy
      - MYSQL_DATABASE=railway
      - MYSQLPORT=52230
    command: ["python3", "main.py"]

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: railway
    ports:
      - "52230:52230"
